version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-server
    ports:
      - "9000:9000"
    depends_on:
      - db
      - redis
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db-connect
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
  redis:
    image: redis
    ports:
      - "6379:6379"
