version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-server
    ports:
      - "3000-3004:3000"
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - "80:80"
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db-connect
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
  
