version: '3'
services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3000-3003:3000"
    command: ["sh", "-c", "sleep 2 && npm start"]

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app1

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db-connect
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
